source 'https://rubygems.org'

gem 'sinatra-base'
gem 'sinatra-assetpack'
gem 'mongoid'
gem 'redis'
gem 'redis-namespace'
gem 'rack'
gem 'whenever'
gem 'haml'
gem 'coffee-script'
gem 'sass'
gem 'sinatra-partial'
